[theme]
primaryColor = "#6C63FF"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#FFFFFF"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"